---
apiVersion: argoproj.io/v1alpha1
kind: Notification
metadata:
  name: notification-2
spec:
  monitorResource:
    Group: argoproj.io
    Resource: workflows
    Version: v1alpha1
  Namespace: default
  notifiers:
    -
      name: slack
      slack:
        channel: testargonotification
        hookurl: "https://hooks.slack.com/services/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"
  rules:
    -
      allConditions:
        -
          jsonPath: status/phase
          operator: eq
          value: Succeeded
      events:
        -
          emailSubject: "Argo Notification Condition Triggered {{.metadata.name}}"
          message: "Workflow = {{.metadata.name}} succesfully completed"
          notificationLevel: info
          notifierNames:
            - slack
      initialDelaySec: 3
      name: rule1
      throttleMintues: 2