apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: kube-notifier-controller
    controller-tools.k8s.io: "1.0"
  name: argo
---
apiVersion: v1
kind: Service
metadata:
  name: kube-notifier-controller-service
  namespace: argo
  labels:
    control-plane: kube-notifier-controller
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    control-plane: kube-notifier-controller
    controller-tools.k8s.io: "1.0"
  ports:
  - port: 443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kube-notifier-controller
  namespace: argo
  labels:
    control-plane: kube-notifier-controller
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: kube-notifier-controller
      controller-tools.k8s.io: "1.0"
  serviceName: kube-notifier-controller-service
  template:
    metadata:
      labels:
        control-plane: kube-notifier-controller
        controller-tools.k8s.io: "1.0"
    spec:
      serviceAccountName: argo
      containers:
      - command:
        - /manager
        image: sarabala1979/argo-kube-notifier:latest
        imagePullPolicy: Always
        name: manager
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SECRET_NAME
            value: $(WEBHOOK_SECRET_NAME)
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/cert
          name: cert
          readOnly: true
        - mountPath: /etc/ssl/certs
          name: ca-certs
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-secret
      - hostPath:
          path: /etc/ssl/certs
        name: ca-certs

---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-secret
  namespace: argo
